apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cardano-mainnet-relay-deployment
  labels:
    app: cardano-mainnet-relay-deployment
spec:
  serviceName: cardano-mainnet-relay
  # Control the number of relays here (you'll need enough volumes to cover them!)
  replicas: 1
  selector:
    matchLabels:
      app: cardano-mainnet-node
      cardano-mainnet-node-type: relay
  template:
    metadata:
      labels:
        # I added two labels to make it easy to select either "all nodes" or
        # "just relays" or just producer node"
        app: cardano-mainnet-node
        cardano-mainnet-node-type: relay
    spec:
      containers:
        - name: cardano-mainnet-relay
          # I'm using the official IOHK/cardano-node image to avoid needing to build anything
          image: inputoutput/cardano-node
          # Expose both the cardano-node port and the /metrics endpoint port.
          ports:
            - containerPort: 12798
            - containerPort: 4000
          # Mount the data volume at /data (see the Volume Claim below)
          volumeMounts:
            - name: data
              mountPath: /data
          # My configuration lives inside the mounted /data folder, and that's also where
          # the db data should be written
          args: ["run", "--config", "/data/configuration/mainnet-config.json", "--topology", "/data/configuration/mainnet-relay-topology.json", "--database-path", "/data/db", "--socket-path", "/data/node.socket", "--port", "4000"]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        # This storageClassName is used on the previously defined volume that
        # provides storage on the host machine
        storageClassName: local-storage-mainnet-relay
        resources:
          requests:
            storage: 25Gi